# Generated by Django 4.0.1 on 2022-03-25 08:59

import author_manager.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('type', models.CharField(default='author', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(blank=True, default='http://127.0.0.1:8000/', max_length=200)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('displayName', models.CharField(default='<django.db.models.fields.related.OneToOneField>', max_length=200)),
                ('github', models.CharField(blank=True, max_length=200)),
                ('profileImage', models.CharField(default=author_manager.models.Author.randomImage, max_length=10)),
                ('birthday', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
                ('remote_followings', models.TextField(blank=True, null=True, validators=[django.core.validators.int_list_validator])),
                ('remote_followers', models.TextField(blank=True, null=True, validators=[django.core.validators.int_list_validator])),
                ('followers', models.ManyToManyField(blank=True, related_name='my_followers', to='author_manager.Author')),
                ('followings', models.ManyToManyField(blank=True, related_name='my_followings', to='author_manager.Author')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('type', models.CharField(default='inbox', editable=False, max_length=30)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='author_manager.author')),
                ('follows', models.JSONField(blank=True, default=list)),
                ('item', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='follow', editable=False, max_length=50)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='author_manager.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='author_manager.author')),
            ],
        ),
    ]
