# Generated by Django 4.0.1 on 2022-03-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='follows',
        ),
        migrations.AddField(
            model_name='inbox',
            name='follows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
