# Generated by Django 4.0.1 on 2022-02-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/', max_length=500),
        ),
    ]
