# Generated by Django 4.0.1 on 2022-02-23 20:25

import author_manager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='follow', editable=False, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/', max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=author_manager.models.Author.short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.CharField(default=author_manager.models.Author.randomImage, max_length=10),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', max_length=50),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('type', models.CharField(default='inbox', editable=False, max_length=30)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='author_manager.author')),
                ('follows', models.ManyToManyField(blank=True, to='author_manager.FriendRequest')),
            ],
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='author_manager.author'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='author_manager.author'),
        ),
        migrations.CreateModel(
            name='FollowerList',
            fields=[
                ('type', models.CharField(default='followers', editable=False, max_length=50)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='author_manager.author')),
                ('items', models.ManyToManyField(blank=True, related_name='items', to='author_manager.Author')),
            ],
        ),
    ]
