# Generated by Django 4.0.1 on 2022-02-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0002_rename_id_author_uuid_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', max_length=50),
        ),
    ]
