# Generated by Django 4.0.1 on 2022-02-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0003_alter_author_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='uuid',
            new_name='id',
        ),
    ]
