# Generated by Django 4.0.1 on 2022-02-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0003_author_followers_author_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='my_followers', to='author_manager.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='my_followings', to='author_manager.Author'),
        ),
    ]
