# Generated by Django 4.0.1 on 2022-02-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_content'),
        ('author_manager', '0004_alter_author_followers_alter_author_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
    ]
