# Generated by Django 4.0.1 on 2022-03-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comment_post'),
        ('author_manager', '0006_author_url_alter_author_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.DeleteModel(
            name='FollowerList',
        ),
    ]
