# Generated by Django 4.0.1 on 2022-03-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0006_author_url_alter_author_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerList',
        ),
    ]
