# Generated by Django 4.0.1 on 2022-02-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0007_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
