# Generated by Django 4.0.1 on 2022-03-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_merge_20220301_1947'),
        ('author_manager', '0007_delete_followerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
    ]
