# Generated by Django 4.0.1 on 2022-03-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_rename_postlike_like'),
        ('author_manager', '0007_delete_followerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(blank=True, to='posts.Like'),
        ),
    ]
