# Generated by Django 4.0.1 on 2022-02-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0008_author_about_author_birthday_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profileImage',
        ),
    ]
