# Generated by Django 4.0.1 on 2022-03-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comment_post_like'),
        ('author_manager', '0008_inbox_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(blank=True, to='posts.Like'),
        ),
    ]
