# Generated by Django 4.0.1 on 2022-02-23 05:46

import author_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0009_remove_author_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.CharField(default=author_manager.models.Author.randomImage, max_length=10),
        ),
    ]
