# Generated by Django 4.0.1 on 2022-02-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0009_friendrequest_inbox_followerlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerlist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='author_manager.Author'),
        ),
    ]
