# Generated by Django 4.0.1 on 2022-03-22 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0008_inbox_likes'),
        ('author_manager', '0010_inbox_item'),
    ]

    operations = [
    ]
