# Generated by Django 4.0.1 on 2022-03-22 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0010_inbox_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='remote_friends',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
