# Generated by Django 4.0.1 on 2022-03-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='incoming_password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='incoming_username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
