# Generated by Django 4.0.1 on 2022-03-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='incoming_password',
        ),
        migrations.RemoveField(
            model_name='node',
            name='incoming_username',
        ),
    ]
