# Generated by Django 4.0.1 on 2022-03-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_node_incoming_password_node_incoming_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='incoming_username',
        ),
    ]
