# Generated by Django 4.0.1 on 2022-03-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remote_author',
            field=models.JSONField(default=dict),
        ),
    ]
