# Generated by Django 4.0.1 on 2022-02-21 10:56

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=posts.models.Post.short_uuid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
