# Generated by Django 4.0.1 on 2022-02-21 11:04

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=posts.models.Post.short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
