# Generated by Django 4.0.1 on 2022-03-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_remote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='remote_author',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
