# Generated by Django 4.0.1 on 2022-03-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_remote_author'),
        ('posts', '0003_alter_like_author'),
    ]

    operations = [
    ]
