# Generated by Django 4.0.1 on 2022-03-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_contenttype'),
        ('posts', '0003_alter_post_remote_author'),
    ]

    operations = [
    ]
