# Generated by Django 4.0.1 on 2022-02-23 20:23

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('author_manager', '0010_author_profileimage'),
        ('posts', '0004_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('type', models.CharField(default='post', max_length=50)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('contentType', models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain')], default='text/plain', max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=posts.models.Comment.short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='author_manager.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
        ),
    ]
