# Generated by Django 4.0.1 on 2022-03-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_merge_20220328_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='object',
            field=models.CharField(default=str, max_length=2048),
        ),
    ]
