# Generated by Django 4.0.1 on 2022-03-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_merge_20220325_0122'),
        ('posts', '0005_like_object'),
    ]

    operations = [
    ]
