# Generated by Django 4.0.1 on 2022-03-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_merge_0004_merge_20220325_0122_0005_like_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
