# Generated by Django 4.0.1 on 2022-02-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
        ('posts', '0007_alter_post_content'),
    ]

    operations = [
    ]
