# Generated by Django 4.0.1 on 2022-02-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_visiableto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visiableTo',
            new_name='visibleTo',
        ),
    ]
