# Generated by Django 4.0.1 on 2022-03-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_merge_0005_comment_0007_alter_post_content'),
        ('posts', '0009_rename_visiableto_post_visibleto'),
    ]

    operations = [
    ]
