# Generated by Django 4.0.1 on 2022-03-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comment_post'),
        ('posts', '0011_alter_comment_post_like'),
    ]

    operations = [
    ]
