# Generated by Django 4.0.1 on 2022-03-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.comment'),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
