# Generated by Django 4.0.1 on 2022-03-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_like_object_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='object_author',
        ),
    ]
