# Generated by Django 4.0.1 on 2022-03-21 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_merge_20220319_1427'),
        ('posts', '0019_alter_like_comment'),
    ]

    operations = [
    ]
