# Generated by Django 4.0.1 on 2022-03-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_merge_20220320_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
